annotations:
  category: TaskTracker
apiVersion: v2
appVersion: 0.24.6
dependencies:
- condition: redis.enabled
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 18.6.3
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 16.4.5
- name: common
  repository: https://bjw-s-labs.github.io/helm-charts
  version: 1.5.1
description: The open-source, self-hostable to-do app. Organize everything, on all
  platforms.
home: https://kolaente.dev/vikunja/helm-chart
icon: https://kolaente.dev/vikunja/helm-chart/raw/main/icon.png
keywords:
- vikunja
- todo
- to-do
- task
- task-tracker
- project-management
- self-hosted
kubeVersion: '>= 1.19.0-0'
maintainers:
- name: Vikunja
  url: https://vikunja.io
name: vikunja
sources:
- https://github.com/go-vikunja/helm-chart
- https://vikunja.io
type: application
version: 1.1.0
